import {
  Loader2,
  Check,
  X,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Plus,
  Minus,
  Trash2,
  Save,
  Edit,
  LogOut,
  ArrowLeft,
  ArrowRight,
  FileText,
  File,
  FilePlus,
  FileEdit,
  History,
  Play,
  Pause,
  Search,
  User,
  Settings,
  Info,
  AlertCircle,
  AlertTriangle,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
  Eye,
  EyeOff,
  type LucideProps,
} from "lucide-react";

export type IconProps = LucideProps;

export const Icons = {
  spinner: Loader2,
  check: Check,
  close: X,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  add: Plus,
  remove: Minus,
  delete: Trash2,
  save: Save,
  edit: Edit,
  logout: LogOut,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  fileText: FileText,
  file: File,
  fileAdd: FilePlus,
  fileEdit: FileEdit,
  history: History,
  play: Play,
  pause: Pause,
  search: Search,
  user: User,
  settings: Settings,
  info: Info,
  warning: AlertTriangle,
  error: AlertCircle,
  sidebarOpen: PanelLeftOpen,
  sidebarClose: PanelLeftClose,
  sidebar: PanelLeft,
  eye: Eye,
  eyeOff: EyeOff,
};
